### ISSUE TITLE
Integrate optional web sockets layer for C/S API.

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-server#153]
Headers only, optionally built on boost::asio (only):
https://github.com/zaphoyd/websocketpp

**Comment by evoskuil** [comment]
It would be nicer to layer a [zeromq-based](http://rfc.zeromq.org/spec:39) implementation over the zeromq client-server API, but the implementations don't look as mature, and there are [cURL dependencies](https://github.com/fanout/zurl). The ASIO-based implementation is much better in these aspects.

**Comment by RojavaCrypto** [comment]
The ASIO one looks kind of old and not well-written. Maybe I'm being judgemental.

Since websockets + JSON is inefficient anyway, what about a Python based daemon that creates the websockets API. A Python server is also hackable for people who want different transports while ZMQ delivers the data locally (which is what it does best - inter-daemon communication).

**Comment by evoskuil** [comment]
Nothing wrong with that as an option, but a couple of considerations.

We worked very hard on getting the Python dependencies out of sx (for bx). Presently, all of the libbitcoin applications can be "installed" by simply placing a statically linked file on any Linux, Mac or Windows box. Adding a second process and a Python dependency breaks that paradigm and complicates both deployment and management.  Additionally, libbitcoin is self-described as a C++ toolkit. Adding a second language means that two language skills are required.

As such I would still want to produce an in-process interface. Bridging zeromq and websockets in-process is straightforward. As a headers only library based on ASIO the only question would be quality/support of the implementation, but looking at it superficially I haven't found any seen any reason for concern. I would really like someone to be able to launch the single file executable, open a browser to the local host, and see the blockchain - that easy.

**Comment by RojavaCrypto** [comment]
ok, I will play with websocketpp and look further at this.

**Comment by RojavaCrypto** [comment]
Also an option:

https://libwebsockets.org/

"Libwebsockets is a lightweight pure C library built to use minimal CPU and memory resources, and provide fast throughput in both directions as client or server."

Active community:

https://libwebsockets.org/pipermail/libwebsockets/2016-June/thread.html

https://github.com/warmcat/libwebsockets

**Comment by evoskuil** [comment]
That looks nice  from a community and quality standpoint, but unless I'm missing something I'd consider the dependency chain a significant problem. Apart from SSL/TLS (which is is probably inescapable) there may also be zlib, libev, lubuv, and sqlite. Given we are ASIO and ZMQ - based I would not be keen on bringing in additional redundant asynchronous I/O dependencies. And every dependency in general is a major headache. Right @thecodefactory ?

**Comment by thecodefactory** [comment]
True about the additional dependencies! @RojavaCrypto: @evoskuil has been working hard to reduce the number of dependencies because they become unmanageable for all of the build configurations and platforms that are supported.  There's a complex enough build/configuration matrix already that it requires very careful consideration on whether bringing in new dependencies is worth the amount of additional maintenance headaches (for all maintainers/builders/testers).  I'm referenced here because some optional bx features I've worked on brought in additional dependencies (e.g. libpng/libqrcode), and while those were easy enough to get working locally on my configuration of GNU/Linux where I develop/test -- they couldn't be properly supported on other platforms without additional work and testing that I frankly didn't think about and ultimately didn't want to deal with (for example, the Windows builds since I don't run Windows).  As @evoskuil mentioned previously, these dependencies also tend to introduce new issues that break static builds of functional single file binaries, which potentially impacts the end users negatively.

**Comment by RojavaCrypto** [comment]
Yep, OK scrap libwebsockets it was just an idea.

But how about a Python daemon for websockets which is simple and easily/quickly improved?

https://stackoverflow.com/questions/14165398/a-good-python-to-exe-compiler

If you use Tornado (which I'd use), you not only get websockets, but also a web server. So you could use Python to make a wrapper around libbitcoin-server that is responsible for stopping, starting and configuring it, as well as displaying the output (that you can view in the web browser). All of this could be wrapped up in a single unpacking .exe

The code for a websockets bridge already exists:

https://github.com/darkwallet/gateway

Python has strong string manipulation and very good template libraries, which means it would be efficient for developing a dynamic hosted website with all modern features (login .etc).

https://wiki.python.org/moin/Templating

Which will be necessary on a production scale. For now, I'd only allow localhost access, but in the future you'll want authentication, tokens, XSS protection, ... lots of stuff which is in Python already.

Also Python is fast to write and have working. Because it's dynamic, you can very easily write code to be plugin based.

I can do a small experiment to try packaging a Python program with some data files, Tornado and a bunch of other libs if @evoskuil feels this is the right direction.

**Comment by RojavaCrypto** [comment]
So I'm clear, I mean Python websockets <-> ZMQ bridge which is responsible for the server, vs directly writing websockets serialization into the server.

Python websockets:
+ Easy to write, quick to modify.
+ Lower entry for other developers, especially with complex web management features.
+ Code already exists.
+ Libraries are better developed for websockets, web, ...

C++ websockets:
+ More performant (but use ZMQ if that matters - websockets is terrible for performance).
+ Directly integrated (is this a good thing?)
+ Less dependencies.
+ More efficient (instead of db <-> ZMQ <-> websockets).

**Comment by evoskuil** [comment]
I'm supportive of an additional library based on Python if someone wants to maintain it, but it would be a different animal than the core C++ libs.

The direct integration simplifies deployment, management and maintenance of the overall system. As for the integrated approach, `websocketpp` has the following benefits (over the other integrated options):

* C++ 11 (optional, can downgrade)
* Boost based (with C++11 optimization to std libs)
* ASIO based (consistent with our proactor design)
* headers only (easy static link for single file build on all platforms)
* single dependency (minimal maintenance for installs and continuous integration)

Given the similarity of the code with our own, it would be straightforward for us to patch issues in it as well. I've had to do this several times with zeromq.

**Comment by lastcanal** [comment]
I have just open-sourced a [Websocket and REST server for BS written in Elixir] (https://github.com/cancoin/bitcoin-voyager) that runs on the massively concurrent Erlang VM. It supports most version 2 API and provides subscriptions (although subscriptions are currently undocumented).

It uses an Erlang port process written C to communicate with BS via CZMQ. Right now there is no ZMQ-cert support in the [Elixir client](https://github.com/cancoin/elixir-libbitcoin-client), but it is very possible to get it working due to using CZMQ under the hood. 

It uses an Erlang NIF written in C++ to parse transactions via libbitcoin: [libbitcoin-nif](https://github.com/cancoin/libbitcoin-nif)

We have also built a [block explorer](https://github.com/cancoin/bitcoin-voyager-web) using this API which can be seen live here: https://voyager.cancoin.co

I'd love to know what you think! We are planning on using this as the blockchain backend of our on-chain multisig OTC marketplace.

**Comment by RojavaCrypto** [comment]
Damn, that's great. Erlang is a strong language, especially for concurrency.

I just spent this month working on something too, using Python asyncio. We should combine our efforts.

Python is the 4th most popular language (Java, C, C++, Python) with strong C/C++ integration, and the asyncio in the new Python 3 is very mature & working well.

https://github.com/rojavacrypto/python-libbitcoin

https://github.com/rojavacrypto/libbitcoin-gateway

Your work looks great. Well done. I'm going to download it all now.

**Comment by lastcanal** [comment]
I'd love to combine efforts. There are still some rough spots that I am working to clean up (especially with libbitcoin-nif) so you might have some trouble building it against libbitcoin master at the moment. I saw this issue and rushed to open-source it ;). The API/names, etc can all be changed fairly easily; I was trying to keep it consistent with the darkwallet gateway but I don't think is anymore. 

Are you thinking of a web management platform for reconfiguring a running libbitcoin server? 

There are 2 ways to integrate C++ into Erlang: one is a Native Implemented Function 
(NIF) which is C/C++ code loaded into the Erlang virtual machine; the other is a Port process, which runs as a separate OS process spawned by Erlang that communicates via stdin/stdout. NIFs can only be used for functions that execute in a very short amount of time, or else it breaks all of Erlang's pre-emptive scheduling, so I don't think that would work. 

A Port process that spawns BS then communicates with it via stdin/stdout could work. A web interface could be built that sends messages to the Port process via a webserver, which in turn would send a message to bs via stdin, which could then reconfigure and reply via stdout. The plus side is the bs process would then be supervised by Erlang's supervisor tree.

Here is the library I use to serialize C++ into erlang terms: https://github.com/goertzenator/nifpp

**Comment by RojavaCrypto** [comment]
OK, well the gateway is for DarkWallet devs who I'm helping so I need to ask their permission if they want to switch to an Erlang websockets gateway (and break the current API). Also in the gateway is other functionality (chat room for coordinating multisigs and coinjoin, price ticket, broadcaster for transactions, radar for seeing sent tx propagation) so we'd need to see about splitting that up. It might simply be too late in development, but I've asked the devs to give a decision and I have to respect their choice. However I did say that it would be better to pool efforts instead of doing duplicate work.

Yes I'm thinking about a web platform for managing the server so admins can login, restart, make config changes, query the database .etc Tornado is a good piece of software for that when combined with a template engine, and supports all the web wsgi stuff (csrf tokens, templates, ... - it's made by facebook for their website).

I think the supervisor route is the best option. Everything in bs that goes to stdout goes to the log files anyway, so reading all the log files gives you access to all the information and this can be extended. Adding another port seems like a bigger headache, and you'd have to duplicate info which is already outputted to the logs.

**Comment by lastcanal** [comment]
Glad you like the block explorer! My brother is a great designer and did all the front end design. We were hoping to make the fastest explorer out there and I think it's close (even with no caching!). 

I am more than happy to help with the Tornado server implementation. it does make sense because because so much functionality is already in python and the new async primitives look really great! Plus python is a much more popular language with more opportunity for people to contribute. All the heavy lifting is done with asyncio so it should work great even without erlang's scheduler ;). 

That being said I have played around with the [txradar](https://github.com/cancoin/elixir-libbitcoin-client/blob/master/lib/libbitcoin/client/sub.ex#L84-L95) and brc to a lesser extent. I also have a lot of code I am prepping to open source that handles fetching prices and even allows scripting the price with Lua (for price alerts, etc.). On top of that I have a chat system working that uses openpgpjs, although it's mostly in ruby, pushing only to erlang when propagating messages.  

The real reason for doing all of this in Elixir/Erlang is because that's where we [sign transactions server side with Ledger hardware wallets](https://github.com/cancoin/bitcoin-hsm).

I'll get your apps running and see where i can help out :)

**Comment by RojavaCrypto** [comment]
Yes the async / await primitives are excellent. Erlang is also a great language, and the concurrency features are cool.

I spoke with the lead DW dev, and he says that we should pool our effort although if it comes down to a significant change for the stack then we should wait until post v1. So right now that means I will develop the gateway under darkwallet/ while I'll add python-libbitcoin to libbitcoin/. That should be for the beta. After beta, we will migrate to v3 bs which includes the radar / brc integrated natively.

The current messaging system is federated but we're also interested to adopt any standards or other services but we'd need feature compatibility. We haven't found anything (that's why we made our own custom protocol).

We are in the development cycle now where we're about to lock features and the API, but post release should give us more flexibility. How does that sound?

**Comment by lastcanal** [comment]
That sounds great. Once the API is all stabilized I'll a take a look and see what can be done to match everything up for a future post v1 release.

**Comment by RojavaCrypto** [comment]
There's a lot of ZMQ <-> WebSocket gateway projects on the internet such as:

https://github.com/tailhook/zerogw

http://code.saghul.net/index.php/2011/09/16/a-zeromq-to-websocket-gateway-take-2/

That's probably a better approach rather than maintaining 2 APIs (with one likely to become out of date). I support the ZMQ API because it is highly efficient and scalable. Unfortunately it can't be used in browsers.

However another solution might be adding websockets support to ZMQ as another protocol.

**Comment by RojavaCrypto** [comment]
Here is the current API used by DW:

https://wiki.unsystem.net/en/index.php/Gateway/Specification

**Comment by evoskuil** [comment]
Implemented!
