### ISSUE TITLE
Failure to validate block following hard shutdown.

### ISSUE THREAD

**Issue by hoffmabc** [libbitcoin/libbitcoin-server#177]
When syncing multiple times from scratch we get stuck with this in the logs

```
23:24:52.215840 DEBUG [poller] Ask for block inventory from [000000000000000003cd1dc31a04841c12461607fd863cee552296769c755199] (29) to [500]
23:24:52.216122 DEBUG [network] Send getblocks [190.10.10.147:8333] (989 bytes)
23:24:52.218293 DEBUG [network] Receive block [190.10.10.147:8333] (495295 bytes)
23:24:52.675780 DEBUG [network] Receive block [190.10.10.147:8333] (795732 bytes)
23:24:52.695090 INFO [blockchain] Block [391309] verify (1014) txs and (2545) inputs
23:24:52.862522 INFO [blockchain] Block [391309] unverified in (0.167) secs or (0.0656189) ms/input
23:24:52.863486 DEBUG [protocol] Channel stopped (outbound) [190.10.10.147:8333] validation of inputs failed
23:24:52.863626 DEBUG [protocol] Connecting to peer [181.25.222.198:8333]
23:24:52.865029 DEBUG [network] Closed a channel and (5) remain open
```

**Comment by evoskuil** [comment]
This block has been synced by the Airbitz server:
```sh
$ bx fetch-header --height 391309
header
{
    bits 403346833
    hash 00000000000000000216e769bf7563b1c4b1a95077e6563101715f2f39be0232
    merkle_tree_hash e8eafd60a1cada103a17679f25efb6ef22793f3b5de7347df3e571814c381720
    nonce 3412147409
    previous_block_hash 000000000000000003cd1dc31a04841c12461607fd863cee552296769c755199
    time_stamp 1451688932
    version 4
}
```
So there must be some difference in the build. I can run a sync tonight to see if I encounter a problem as well. Is your build `--with-consensus` (default) or `--without-consensus` at the head or tag of `version2` or is it using the prebuilt-binary?

**Comment by evoskuil** [comment]
As a workaround you can checkpoint this block in config.

**Comment by hoffmabc** [comment]
I checkpointed and it got stuck again...not sure what's up with it.

**Comment by hoffmabc** [comment]
It was built with 
```
./install.sh CXXFLAGS=-Os --without-tests --enable-ndebug --disable-shared --build-boost --prefix=/home/bitcoin
```
so I'm assuming --with-consensus

**Comment by hoffmabc** [comment]
I just rebuilt on 2.4.0 instead of just 2 and got this so same result:

```
11:49:47.671758 INFO [blockchain] Block [391526] unverified in (2.602) secs or (0.559209) ms/input
11:49:47.671837 ERROR [poller] Error storing block [0000000000000000051ce1f9dd503c3f12f6eef1efc21575f8d78a18e1d56c22] validation of inputs failed
11:49:47.706742 INFO [protocol] Connected to peer [172.86.178.46:8333] (2 total)
11:49:49.699896 INFO [protocol] Connected to peer [70.35.98.39:8333] (2 total)
11:49:50.391958 INFO [blockchain] Block [391526] verify (2098) txs and (4653) inputs
11:49:50.522875 INFO [protocol] Connected to peer [170.15.240.5:8333] (3 total)
11:49:51.646118 INFO [protocol] Connected to peer [173.224.246.184:8333] (4 total)
11:49:52.642172 INFO [protocol] Connected to peer [62.210.247.136:8333] (5 total)
11:49:53.048932 INFO [blockchain] Block [391526] unverified in (2.656) secs or (0.570815) ms/input
11:49:53.049075 ERROR [poller] Error storing block [0000000000000000051ce1f9dd503c3f12f6eef1efc21575f8d78a18e1d56c22] validation of inputs failed
11:49:53.091306 INFO [protocol] Connected to peer [64.111.58.118:8333] (5 total)
11:49:53.898017 INFO [blockchain] Block [391526] verify (2098) txs and (4653) inputs
11:49:56.835657 INFO [blockchain] Block [391526] unverified in (2.937) secs or (0.631206) ms/input
11:49:56.835736 ERROR [poller] Error storing block [0000000000000000051ce1f9dd503c3f12f6eef1efc21575f8d78a18e1d56c22] validation of inputs failed
11:49:56.948410 INFO [blockchain] Block [391526] verify (2098) txs and (4653) inputs
11:49:57.967052 INFO [protocol] Connected to peer [37.135.212.47:8333] (5 total)
11:49:59.779268 INFO [blockchain] Block [391526] unverified in (2.83) secs or (0.60821) ms/input
11:49:59.779365 ERROR [poller] Error storing block [0000000000000000051ce1f9dd503c3f12f6eef1efc21575f8d78a18e1d56c22] validation of inputs failed
11:49:59.960810 INFO [blockchain] Block [391526] verify (2098) txs and (4653) inputs
ZAUTH I: ALLOWED (NULL)
11:50:03.056274 INFO [blockchain] Block [391526] unverified in (3.095) secs or (0.665162) ms/input
11:50:03.056372 ERROR [poller] Error storing block [0000000000000000051ce1f9dd503c3f12f6eef1efc21575f8d78a18e1d56c22] validation of inputs failed
11:50:03.358624 INFO [blockchain] Block [391526] verify (2098) txs and (4653) inputs
^C
```

**Comment by evoskuil** [comment]
OK. I'm still getting synced up. Until I have a repro there isn't much I can do.

**Comment by evoskuil** [comment]
On each of these runs have you been using the same blockchain store, or has it been rebuilt each time?

**Comment by hoffmabc** [comment]
I tried both. I did one and then check pointed it and it kept getting stuck then I did a full resyncing and it got stuck again. I'm resyncing once more.

**Comment by evoskuil** [comment]
Okay, if it happens more than once on the same blocks with a full resync then there is little chance it is the result of a database corruption. In version2 there are situations that can result in corruption without a hard shutdown, so I just want to rule that out. I have resolved these conditions for version3.

**Comment by evoskuil** [comment]
I just validated **391309** using a consensus build.

**Comment by evoskuil** [comment]
I've also passed the other problem block, currently at **391725** and progressing.

**Comment by evoskuil** [comment]
My test was using a binary from the latest release. I'm reevaluating using your build. The only thing I can think of is some impact due to a change in the release of consensus for 0.12.0. The server binary release was built prior to the consensus 0.12.0 final release. You could try using the downloadable binary against your stuck chain to see if it validates it.

**Comment by evoskuil** [comment]
Also, in the `error.log` do you have any occurrences of:
```
Invalid input [...]
```

**Comment by hoffmabc** [comment]
yes i do

**Comment by evoskuil** [comment]
Could you determine if the tx(s) that are referenced in the errors are actually present in the store? You can use [bx fetch-tx](https://github.com/libbitcoin/libbitcoin-explorer/wiki/bx-fetch-tx).

**Comment by evoskuil** [comment]
I just validated **391309** using the same build, on Ubuntu:
```
./install.sh CXXFLAGS=-Os --without-tests --enable-ndebug --disable-shared --build-boost --prefix=/home/eric
```
So I currently have no repro. Have you confirmed that the tx is/isn't present?

**Comment by evoskuil** [comment]
Do you have the debug logs since first creating the store(s)?

These should be inspected for evidence of hard shutdowns. Seek the `================= Startup =================` entries and then look for controlled shutdown immediately preceding. If you find any evidence of uncontrolled shutdown (especially during sync) it is likely that the store has become corrupt due to an interrupted write. Symptoms of this can be delayed for some time and there's currently no way to inspect for it.

Bottom like is that you need to make sure you control process shutdown. If you are using a remote management tool it's very possible that it is killing the process before allowing it time to shut down. Shutdown can take a lot longer during sync and on an HDD.

**Comment by hoffmabc** [comment]
We use supervisor to control the service but I suppose it is possible that it was shut down improperly I guess. The only issue I found was that it was happening before the service ever died even once when I was resyncing. 

For now I've built a completely clean new VPS and I'm trying to resync there and have not seen an issue so perhaps the VPS is corrupted somehow.

**Comment by evoskuil** [comment]
I believe that by default supervisor will kill the process if it does not close within 10 seconds of a termination command. This is too low during sync, and it if happens during sync a corruption is very likely. The corruption can go on for a long time without being detected. You should change the supervisor configuration to increase the kill time frame. If you are using an SSD 60 secs should be sufficient even during sync. Otherwise you might need more time.

It is easy to see a hard shutdown in the logs and if you encounter this problem that is what you should look for. I just went through the same process with another user. 3 of 5 servers detecting corruption during sync, the logs indicated hard shutdowns. They are also using supervisor.

**Comment by lclc** [comment]
We also use supervisor at Airbitz. I've added
> stopwaitsecs=60

to the supervisor conf file.

**Comment by hoffmabc** [comment]
Ok great thanks. Perhaps this is what has been causing issues this whole time. Will try and get back.

**Comment by lclc** [comment]
Same problem, also with resyincing from scratch and stopwaitsecs=60

Will upload the logs later.

**Comment by evoskuil** [comment]
The stop time isn't the essential issue. Do you know if there was a hard shutdown?

**Comment by lclc** [comment]
I did not make any manual shutdown.

The error.log file: https://paste.ubuntu.com/15916560/
The last 2000 lines from console.log: https://paste.ubuntu.com/15916746/
The last 10000 lines from debug.log: https://paste.ubuntu.com/15916746/ http://paste.ubuntu.com/15916794/

It seems to have a re-start in the log, but it's not from me. Although supervisor auto-restarts it when it crashes.

**Comment by evoskuil** [comment]
Lines 959 and 1259 of the debug log indicate a hard shutdown. So the issue is not in validation, it's in shutdown. Next step is to determine whether the process is being shut down by the OS or if it is bringing itself down.

I suspect that it's actually both, and based on configuration. Notice that the validation time spikes immediately before the two shutdowns. This is an indication of a performance hit, which would only be caused by excess RAM consumption. This could be caused by excessive block backlogging or excessive paging, or both. The way I was able to control this in version2 was to use checkpoints and a single peer during sync. You are running 8 peers outgoing, and several incoming.

Version2 is a lot better, but this resolution was just a workaround. It still requires some manual care to get fully synced. Once you are there it should be a problem. And if there is a hard shutdown, at that point it's unlikely to affect data since writes are infrequent (about .01% of time running).

You can either validate with 1 outgoing and 0 incoming, with the block pool set to something reasonable (e.g. 20), or use a checkpoint near the top, or a little of both if you don't want the checkpoint too high (20 blocks from the top would be perfectly reasonable, especially if you are relying on a 20 block pool.

**Comment by hoffmabc** [comment]
After making sure the server I was using had ample resources (RAM and disk space) and making sure supervisord wasn't corrupting the db on shut down I haven't seen any problems. Log rotation was a must as it stopped responding to calls once the log file go too large.

**Comment by evoskuil** [comment]
@hoffmabc Cool, thanks for the feedback.

Dynamic [log rotation](https://github.com/libbitcoin/libbitcoin-server/issues/107) and [statsd](https://github.com/libbitcoin/libbitcoin/issues/359) are on the backlog. Need to swap out our logging with [boost log](https://github.com/libbitcoin/libbitcoin/issues/307) first.

**Comment by lclc** [comment]
I have 8 GB or RAM and 200 GB SSD (used 139.1 GB). Should be enough?

So the solution would be that libbitcoin-server just drops a few connections when RAM usage gets too high?

My config file:

inbound_connection_limit = 8
outbound_connections = 8
relay_transactions = true

[blockchain]
block_pool_capacity = 50

[node]
transaction_pool_capacity = 100000

So I need to change the config to something else during sync and then change it back? Would be cool to not have to do that so I can startup nodes with a Vagrant file without ever having to touch them again when needed.

**Comment by evoskuil** [comment]
> I have 8 GB or RAM and 200 GB SSD (used 139.1 GB). Should be enough?

Yes, this is fine. The database actual size is much smaller so there is plenty of room for growth. Version3 contracts the files to logical size on stop, so you can see what the actual size it. When it starts up those sizes will increase by 50%. A fully-synced and indexed mainnet database is about 90GB, so expansion up to 135GB. There's a little variation from version2 since it never contracts. You might want to keep the logs on the SSD as well. 8GB is what I use. I consider 8RAM/200SSD/4Core the min spec and it's what I run.

During sync (under a checkpoint) you should run the defaults for the other values. What you have above is fine once you are synced.

> So I need to change the config to something else during sync and then change it back?

Yes, see: https://github.com/libbitcoin/libbitcoin-server/wiki/Configuration-Settings#default-settings

> Would be cool to not have to do that so I can startup nodes with a Vagrant file without ever having to touch them again when needed.

I'm spending most of my time on this sort of thing in version3.

**Comment by lclc** [comment]
My config file:

```
[network]
inbound_connection_limit = 8
outbound_connections = 8
relay_transactions = true

[blockchain]
block_pool_capacity = 50

[node]
transaction_pool_capacity = 100000

[server]
publisher_enabled = true
queries_enabled = true
```

So the only difference is block_pool_capacity, which is (according to the docs) "The maximum number of orphan blocks in the pool". So this shouldn't be a problem for the RAM, since  that would mean max 50 MB extra ?

And transaction_pool_capacity set to 100 000 instead of the default 2000. Guess that's the problem. I don't remember why I set that so high.. Will set it back to the default.

**Comment by evoskuil** [comment]
@lclc Those are the settings that need to be change *after* sync completes. I would not expect the configuration above to complete a sync. During sync you should use the defaults for those values, [listed in this section](https://github.com/libbitcoin/libbitcoin-server/wiki/Configuration-Settings#configuration-settings).

```ini
[network]
inbound_connection_limit = 0
outbound_connections = 0
relay_transactions = false

[blockchain]
block_pool_capacity = 1

[node]
transaction_pool_capacity = 0

[server]
publisher_enabled = false
queries_enabled = false
```

The block pool is fine at 50 as long as you are fully synced. It should be 1 during sync (along with the other defaults and a high checkpoint). The block pool will always fill up during sync, if only from block announcements. Each block in the pool created a time cost that is multiplied by each block received, so the cost is nonlinear.


A large transaction pool is fine (after sync). It can slow some things down a bit and linearly increases memory consumption as it is populated.

**Comment by evoskuil** [comment]
Is this all good as long as hard shutdowns are avoided?

**Comment by hoffmabc** [comment]
I haven’t had any problems now with the adjustment to supervisorctl and rotating logs. Once logs get huge the server has a hard time responding so other than that it has looked good. Thanks.

**Comment by evoskuil** [comment]
Great, thanks.
