### ISSUE TITLE
' ////ATTACH(transaction_pool, broadcast, node_);' is not used.

### ISSUE THREAD

**Issue by betachen** [libbitcoin/libbitcoin-server#302]
in file: src/lib/client
```cpp
void proxy::protocol_broadcast_transaction(error_handler on_error,
    empty_handler on_reply, const chain::transaction& tx)
{
    // still using protocol.broadcast_transaction
    send_request("protocol.broadcast_transaction", tx.to_data(),
        on_error,
        std::bind(decode_empty,
            _1, on_reply));
}
```

in file : src/workers/qurey_worker.cpp
```cpp
    ////ATTACH(transaction_pool, broadcast, node_);
    ATTACH(protocol, broadcast_transaction, node_);
```

However, we found that some comments in 
// blockchain.broadcast_transaction is deprecated in v3 (deferred).
// transaction_pool.broadcast (with radar) is new in v3 (deferred).

Is that not be done yet in v3?
I have seen the comments of TODOs:
// TODO: conditionally subscribe to penetration notifications.
// TODO: broadcast transaction to receiving peers.

**Comment by evoskuil** [comment]
The `protocol.broadcast_transaction` call remains usable in v3. The term "deprecated" means it may be removed in the next major release. I've removed the term "deferred" from that since the deprecation is currently valid (it may go away in v4).

The `transaction_pool.broadcast` calls is not implemented and is intended to extend tx broadcast with radar functionality. The term deferred means that it hasn't been done yet (i.e. in v3) but is planned for integration in the current major release (v3.x).

**Comment by betachen** [comment]
thank you Eric. @evoskuil
