### ISSUE TITLE
can't update block

### ISSUE THREAD

**Issue by docliff** [libbitcoin/libbitcoin-server#398]
when block reach some height，bs can keep connecting outbound channel，but it will not update block any more，I didn't see any error message in log.

**Comment by evoskuil** [comment]
Hi @docliff. What height? What is the hash of the last block synced? Look in the debug.log for indications.

**Comment by docliff** [comment]
The node start height in mainnet，when it reach about 400000 seems to get stuck，become slower and slower.

**Comment by docliff** [comment]
@evoskuil The node start height in mainnet，when it reach about 400000 seems to get stuck，become slower and slower.

**Comment by evoskuil** [comment]
Slow is very different from stuck. Is it progressing?

**Comment by docliff** [comment]
Yes. It is processing, I get debug info in log "Ask .. for headers after [000000000000000003cac6de19f0c0a00d5aa27ea2d7bfa19dfa2104201457df]". Is that mean node can't get higher block in that hash?

**Comment by evoskuil** [comment]
By "progressing" (not processing) I mean is the chain increasing in height? Asking for headers is normal node operation and does not imply that it is stuck. If you would send me a recent section of the debug.log I can probably tell you what is happening.

**Comment by docliff** [comment]
Chain height is not increasing, I cut some log section in the attach as showing below that I guess may lead the problem.
[debug.txt](https://github.com/libbitcoin/libbitcoin-server/files/1012856/debug.txt)

**Comment by evoskuil** [comment]
Have you ever deleted the `flush_lock` file?

**Comment by evoskuil** [comment]
I assumed this, since the only possible cause for the error is store corruption. The purpose of the `flush_lock`  is to prevent start up with a corrupted store. If you delete the file and start up, future behavior is undefined (unpredictable) as the store is corrupt. The file is left behind when you terminate the process while there exists an unflushed write.

You can set the `database.flush_writes` configuration option so that each write is flushed immediately, however this significantly slows initial block download. In any case, you must delete your store and reinitialize it, as the store is corrupt.

**Comment by docliff** [comment]
@evoskuil all right, thank you.
