### ISSUE TITLE
libboost-all-dev & Ubuntu 20.04 - One minor version behind

### ISSUE THREAD

**Issue by rilesdun** [libbitcoin/libbitcoin-server#555]
Following the documentation on a fresh Ubuntu 20.04 server (fully updated) - I installed boost as the following:

```
Next install the [Boost](http://www.boost.org/) (1.57.0 or newer) development package:

$ sudo apt-get install libboost-all-dev
```
It says as long as 1.57.0 or newer, it is "should" be good to go. Though after running the install script, I am hit with the following:

```
checking for boostlib >= 1.72.0 (107200)... configure: We could not detect the boost libraries (version 1.72.0 or higher). If you have a staged boost library (still not insn.  If you are sure you have boost installed, then check your version number looking in <boost/version.hpp>. See http://randspringer.de/boost for more documentation.
configure: error: Boost 1.72.0 or later is required but was not found.
```

The default in Ubuntu 20.04 repos is boost 1.71.0 - Can the documentation be updated to include the proper way to install boost 1.72.0?

**Comment by pmienk** [comment]
I'll be working on updating the documentation. However you may want to try executing the `./install.sh --with-icu --build-icu --build-boost --prefix=<prefix path>` and allowing the script to attempt to install the dependencies and `bs` into a prefix directory. If you experience problems then I would be happy to try and help you.

Installing boost manually is a bit tedious and appears to have documented issues specifically related to Ubuntu 20.04. I've successfully built via Ubuntu 22.04, however there is a known issue related to pthread documented as a 20.04 issue which required a single line edit in sources to complete compilation. Strangely, this doesn't come up via `ubuntu-latest` via Github Actions, and the `install.sh` succeeds, so that would be the place to start.
